l2x6/cq-maven-plugin

src/main/java/org/l2x6/cq/PomTransformer.java
src/main/java/org/l2x6/cq/PromoteExtensionMojo.java

@ppalaga proposal to set nativeSince while promoting an extension to native.

Set nativeSince property when promoting an extension to native

---

README.adoc
camel-spring-boot-prod-maven-plugin/pom.xml
camel-spring-boot-prod-maven-plugin/src/main/java/org/l2x6/cq/camel/maven/prod/CamelSpringBootProdExcludesCheckMojo.java
camel-spring-boot-prod-maven-plugin/src/main/java/org/l2x6/cq/camel/maven/prod/CamelSpringBootProdExcludesMojo.java
pom.xml

Initial commit of camel-spring-boot-prod-maven-plugin, documentation additions.

Initial commit of camel-spring-boot-prod-maven-plugin, documentation additions.

---

pom.xml
prod-maven-plugin/pom.xml
prod-maven-plugin/src/main/java/org/l2x6/cq/maven/prod/ProdExcludesMojo.java
prod-maven-plugin/src/main/java/org/l2x6/cq/maven/prod/TransitiveDependenciesMojo.java
prod-maven-plugin/src/test/expected/check-initial/target/prod-excludes-work/poms/bom/pom.xml
prod-maven-plugin/src/test/expected/check-new-supported-extension/poms/bom/pom.xml
prod-maven-plugin/src/test/expected/check-new-supported-extension/target/prod-excludes-work/poms/bom/pom.xml
prod-maven-plugin/src/test/expected/prod-excludes-initial/poms/bom/pom.xml
prod-maven-plugin/src/test/expected/prod-excludes-new-supported-extension/poms/bom/pom.xml

instead of looking into camel-bom

Decide Camel artifact flavor based on own transitive dependencies

---

camel-spring-boot-prod-maven-plugin/src/main/java/org/l2x6/cq/camel/spring/boot/maven/prod/CamelSpringBootProdExcludesMojo.java

Change prefix in the properties for the camel-spring-boot-prod-maven-plugin to "csb" to match camel-spring-boot

Change prefix in the properties for the camel-spring-boot-prod-maven-plugin to "csb" to match camel-spring-boot

---

camel-prod-maven-plugin/src/main/java/org/l2x6/cq/camel/maven/prod/CamelProdExcludesMojo.java
camel-spring-boot-prod-maven-plugin/src/main/java/org/l2x6/cq/camel/spring/boot/maven/prod/CamelSpringBootProdExcludesMojo.java

CSB prod-maven-plugin was ignoring lines with trailing whitespace - we should strip the lines before adding them to the list
https://github.com/jboss-fuse/camel-spring-boot/commit/c2f6481d3ab346c2def38a429c43c50cde546e9b

CSB prod-maven-plugin was ignoring lines with trailing whitespace - we should strip the lines before adding them to the list

---

camel-prod-maven-plugin/src/main/java/org/l2x6/cq/camel/maven/prod/CamelProdExcludesMojo.java
pom.xml

Started trying to create a camel-3.17.0-branch product branch and ran into a few errors - camel-allcomponents has moved, so we now check it's new location, a few typos fixed, and upgrade of the camel-community version.

Do a file exists check, fix a few typos, upgrade camel-community version

---

README.adoc
release.sh

@jamesnetherton would you like to test with 
```
./release.sh 3.2.4 3.2.5-SNAPSHOT
```

Document releasing

---

common/src/main/java/org/l2x6/cq/common/CqCommonUtils.java
common/src/main/java/org/l2x6/cq/common/PomModelCache.java
common/src/main/java/org/l2x6/cq/common/sync/SyncExpression.java
common/src/main/java/org/l2x6/cq/common/sync/SyncExpressions.java
common/src/test/java/org/l2x6/cq/common/sync/SyncExpressionsTest.java
common/src/test/resources/sync-versions/bom-pom.xml
common/src/test/resources/sync-versions/some-parent-pom.xml

Evaluate @sync expression in proper order

---

prod-maven-plugin/src/main/java/org/l2x6/cq/maven/prod/ProdInitMojo.java

CEQ-6528 Add a step preventing CEQ-6517 to cq-maven-plugin prod-init

---

common/src/main/java/org/l2x6/cq/common/FlattenBomTask.java

Be able to workaround https://github.com/quarkusio/quarkus/issues/36952 alias https://github.com/jboss/jboss-parent-pom/issues/236

Honor onCheckFailure in flatten-bom mojo

---

maven-plugin/pom.xml
maven-plugin/src/main/java/org/l2x6/cq/maven/doc/AbstractDocGeneratorMojo.java
maven-plugin/src/main/java/org/l2x6/cq/maven/doc/UpdateDocPageMojo.java
pom.xml

Blocked by https://github.com/quarkusio/quarkus/pull/37911

Render JavaDoc @since version in the config option documentation

---

prod-maven-plugin/src/main/java/org/l2x6/cq/maven/prod/ProdExcludesMojo.java
prod-maven-plugin/src/main/java/org/l2x6/cq/maven/prod/TransitiveDependenciesMojo.java

@jamesnetherton could you please test this on MacOS?
The changed config would be as follows:
```json
"transitiveDependencyReplacements": {
"com.aayushatharva.brotli4j:native-osx-aarch64": "com.aayushatharva.brotli4j:native-linux-x86_64"
},
"ignoredTransitiveDependencies": [
"net.openhft:affinity"
]
```
The docs for the two new options to add to https://github.com/jboss-fuse/camel-quarkus/blob/3.8.0-product/product/README.adoc would be as follows:
```
* `transitiveDependencyReplacements` - a map from `groupId:artifactId` to `groupId:artifactId`. Any artifacts matching some given key will be replaced by the corresponding value when compiling the reports in `product/src/main/generated/transitive-dependencies-*.txt`. The primary purpose of these replacement is to keep the report reproducible …
```

Add capability to filter or replace artifactIds activated by OS specific profiles

---

prod-maven-plugin/pom.xml
prod-maven-plugin/src/main/java/org/l2x6/cq/maven/prod/SyncExamplesFromUpstreamMojo.java
prod-maven-plugin/src/test/java/org/l2x6/cq/maven/prod/SyncExamplesFromUpstreamMojoTest.java

* Handle temporary artifacts
* Fix project version resolution for synced example projects

Sync examples mojo fixes

---

maven-plugin/src/main/java/org/l2x6/cq/maven/doc/UpdateDocPageMojo.java
pom.xml

Adapt to Quarkus 3.16

---

alias-fastinstall-quickly-extension/pom.xml
camel-prod-maven-plugin/pom.xml
camel-spring-boot-prod-maven-plugin/pom.xml
common/pom.xml
filtered-external-enforcer-rules/pom.xml
maven-plugin/pom.xml
pom.xml
prod-maven-plugin/pom.xml
test-utils/pom.xml

Doing this manually as it failed during the 4.17.1 release.

Next is 4.17.2-SNAPSHOT

---

prod-maven-plugin/src/main/java/org/l2x6/cq/maven/prod/ProdInitMojo.java

@zhfeng as per recent discussion. WDYT?
I tested and it seems to work ok.

Make ProdInitMojo transform jxmpp sync tag to use camel-community-version

---

.github/project.yml

Trigger release 4.17.2

---

prod-maven-plugin/src/main/java/org/l2x6/cq/maven/prod/ProdInitMojo.java

Support for changes presented by https://github.com/jboss-fuse/camel-quarkus/pull/472

Support to copy camel-quarkus-cics extension from prev branch

---

prod-maven-plugin/src/main/java/org/l2x6/cq/maven/prod/PlatformOverridesMojo.java
prod-maven-plugin/src/main/java/org/l2x6/cq/maven/prod/Product.java
prod-maven-plugin/src/test/expected/check-initial/product/src/main/resources/camel-quarkus-product-source.json
prod-maven-plugin/src/test/expected/check-new-supported-extension/product/src/main/resources/camel-quarkus-product-source.json
prod-maven-plugin/src/test/expected/prod-excludes-initial/product/src/main/resources/camel-quarkus-product-source.json
prod-maven-plugin/src/test/expected/prod-excludes-new-supported-extension/product/src/main/resources/camel-quarkus-product-source.json
prod-maven-plugin/src/test/projects/prod-excludes/product/src/main/resources/camel-quarkus-product-source.json
prod-maven-plugin/src/test/resources/camel-quarkus-product-source-with-new-extension.json

Configurable support level attribute name in RHBQ platform metadata overrides

---

.github/dependabot.yml
pom.xml

Downgrade to Maven Resolver 1.9.24, disable major Dependabot upgrades for it

---

prod-maven-plugin/src/main/java/org/l2x6/cq/maven/prod/ProdInitMojo.java

https://issues.redhat.com/browse/CEQ-11677

quarkus-extension-maven-plugin should refer to community version of camel-quarkus-debug
